### ISSUE TITLE
No longer working after Chrome update

### ISSUE THREAD

**Issue by giantsloth** [alter-ego/google-calendar-scroll-disabler#11]
The plugin is no longer working after a recent update to Google Chrome.

I'm running Chrome 68.0.3440.106 on OS X 10.11.6. A couple commenters in the Chrome web store are also reporting the issue.

Thanks to the developer(s) for your past work on this plugin; I've found it very useful.

**Comment by scotthue** [comment]
This is also not working for me, Chrome 68.0.3440.106 on OS X 10.13.6.

**Comment by AgrimPrasad** [comment]
This should be fixed by https://github.com/alter-ego/google-calendar-scroll-disabler/pull/12 apparently.

@hamen Please take note thanks!

**Comment by knumat** [comment]
This change appears to be functional for me.

The only issue I've noticed after this change is that if I click an arrow button at the top to change months, and then move the mouse scroll wheel right away, I am able to scroll freely for about 1 second or so (until the page load completes). I am a new user of this extension, though, so perhaps this is a pre-existing issue?

**Comment by knumat** [comment]
Hi @hamen ,

I took a look, and I think I discovered the root issue.

The issue was that the data-viewfamily mutation no longer occurs when the page is loaded.
Now, the data-viewfamily mutation only occurs when the user changes views.
Thus, we need to disable scrolling once when the page is initially loaded.

Could you take a look at #15 and see if it works for you?

**Comment by x1c0** [comment]
Hi @knumat,

I quickly tried it and #15 does not work for me, as soon as I slightly touch the mouse "wheel" the months go crazy :(

Thanks for trying to fix this super annoying issue 😩 

ps. using Version 69.0.3497.100

**Comment by knumat** [comment]
Hi @x1c0 ,

Thanks for the feedback on this!  I did notice one add thing this morning.  Right after a page load/reload, the scroll wheel is properly disabled (month does not change).  However, if I manually change the month with the left or right arrow button at the top, then any further activity on the scroll wheel does indeed change the month.  I'll see if I can fix this sometime today.

Could you try reloading the webpage to see if the scroll wheel is disabled at that point?  If so, then I think we are seeing the same issue.  If not, perhaps you are seeing a different issue than I am?

**Comment by knumat** [comment]
@x1c0 I did some more work to disable scrolling after changing the month.  It ended up requiring some significant changes to the code.  Could you try my updates in #15 and let me know how it works for you?

**Comment by x1c0** [comment]
Hi @knumat,

It works like a charm 👍 

Thank you!

**Comment by hamen** [comment]
A new release is rolling out. Please, give it a try.
