### ISSUE TITLE
Still does not work .4

### ISSUE THREAD

**Issue by haydaw** [alter-ego/google-calendar-scroll-disabler#17]
Hello,

I've been following your progress, and while greatly appreciated, I saw you mentioned it is finally resolved, however after uninstalling and redownloading from the chrome store the extension does not disable scrolling. Downloaded again on 10/7/18.

**Comment by edwinallan** [comment]
same here unfortunately

**Comment by hamen** [comment]
A new release is rolling out. Please, give it a try.

**Comment by haydaw** [comment]
Seems to be working now, wonderful! Appreciate all of the hard work.
