### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by brendanfalkowski** [alter-ego/google-calendar-scroll-disabler#4]
I think Google Calendar changed something because this stopped working today (noooooo!). Maybe the event is on a different element now?

**Comment by hamen** [comment]
Thank you for "pushing me off off couch" :smile: 
I knew this day would come: #2 
A new release should be available in minutes on Chrome Web Store.
Thank you again

**Comment by brendanfalkowski** [comment]
Awesome, thanks.

**Comment by brendanfalkowski** [comment]
Works again, thanks!
