### ISSUE TITLE
Why does it need to read/change data on my calendar?

### ISSUE THREAD

**Issue by LunaticoCR** [alter-ego/google-calendar-scroll-disabler#5]
Hi,

I installed this extension not so long ago an loved it. I noticed recently (perhaps after Chrome updated itself) that now the extension is disabled and it wants me to grant new permissions to read and change data on my calendar. Why does it need this? Don't really feel comfortable allowing this new permissions.

![screen shot 2015-10-20 at 09 51 42](https://cloud.githubusercontent.com/assets/2124383/10602509/a8c9c496-7710-11e5-8bed-b5cb32e5d385.png)

Thanks!

**Comment by hamen** [comment]
Hi Daniel,
I suppose the permission is needed to monitor the Google Calendar domain.
The whole extension source code is here:
https://github.com/alter-ego/google-calendar-scroll-disabler/blob/master/code/content.js
Google Calendar changed its url, as you can read about here: https://github.com/alter-ego/google-calendar-scroll-disabler/issues/2
The new version simply updates to the new url:
https://github.com/alter-ego/google-calendar-scroll-disabler/commit/a60dc6d648f5343690e0a6578ac1638f9e07a856
Nothing to worry about.
Ivan

**Comment by LunaticoCR** [comment]
That makes sense, thank very much for your quick reply.
